version: 0.2

env:
  git-credential-helper: yes
  secrets-manager:
    dockerhub_username: $DOCKER_SECRET_ID:username
    dockerhub_password: $DOCKER_SECRET_ID:password

phases:
  install:
    runtime-versions:
      nodejs: 20.x
    commands:
      - apt-get install jq
      - wget https://github.com/mikefarah/yq/releases/download/v4.23.1/yq_linux_amd64 -O /usr/bin/yq && chmod +x /usr/bin/yq
      - pip3 install docker-compose
      - npm install --silent --progress=false -g npm@8.19.4
      - npm install --silent --progress=false -g yarn
      # https://aws.amazon.com/es/premiumsupport/knowledge-center/codebuild-docker-pull-image-error/
      - docker login -u $dockerhub_username -p $dockerhub_password

  build:
    commands:
      # TODO: change that when the environments are more stable
      # - yarn restoreSetup:aws test
      # - make test_unit_integration
      - make test_unit

  post_build:
    commands:
      - make clean